# Generated by Django 4.2.4 on 2023-08-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departements',
            name='images',
            field=models.ImageField(upload_to='treatments/images/%y/%m/%d/'),
        ),
    ]
