# Generated by Django 4.2.4 on 2023-08-18 22:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(blank=True, max_length=225, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('images', models.ImageField(upload_to='treatment/images/%y/%m/%d/')),
            ],
        ),
    ]
