# Generated by Django 4.2.4 on 2023-08-18 16:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(max_length=225)),
                ('copyright', models.CharField(max_length=225)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=225)),
            ],
        ),
    ]
