# Generated by Django 4.2.4 on 2023-08-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='copyright',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
