# Generated by Django 4.2.4 on 2023-08-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=225)),
                ('symptoms', models.CharField(max_length=225)),
                ('departements', models.CharField(max_length=225)),
                ('doctors', models.CharField(max_length=225)),
            ],
        ),
    ]
