# Generated by Django 4.1.2 on 2023-08-20 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointements',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 13, 35, 48, 950866, tzinfo=datetime.timezone.utc)),
        ),
    ]
