# Generated by Django 4.2.4 on 2023-08-29 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointement', '0002_alter_appointements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointements',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 10, 16, 58, 66861, tzinfo=datetime.timezone.utc)),
        ),
    ]
