# Generated by Django 4.2.4 on 2023-08-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departements',
            new_name='Doctors',
        ),
    ]
